### ISSUE TITLE
plugin-photos插件报错

### ISSUE THREAD

**Issue by zuoer96** [Roozenlz/halo-theme-aurora#28]
### 是什么版本出现了此问题？

plugin-photos版本 1.1.0 Halo 版本要求 2.9.0 主题 hexo-theme-aurora

### 发生了什么？

按照图库插件后，访问/photos路由会报错

**Comment by Roozenlz** [comment]
这款主题不支持图库，可以安装timeplus主题

**Comment by zuoer96** [comment]
> timeplus
不想换主题，这款主题很好看，后续有计划类似的功能吗，或者集成timeplus

**Comment by Roozenlz** [comment]
不需要换主题，timeplus主题与其他主题不同，可以作为副主题使用，具体请看主题的使用说明

**Comment by zuoer96** [comment]
> 不需要换主题，timeplus主题与其他主题不同，可以作为副主题使用，具体请看主题的使用说明

好的，感谢答复，我去看一下这款主题
